<?php

namespace Database\Seeders;

use App\Models\Nation;
use Illuminate\Database\Seeder;

class NationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $nation = new Nation();
        $nation->name = "أفغاني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ألباني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "جزائري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "أمريكي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "أندوري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "أنغولي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "انتيغوا";
        $nation->save();
        $nation = new Nation();
        $nation->name = "أرجنتيني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "أرميني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "أسترالي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "نمساوي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "أذربيجاني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "باهامى";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بحريني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بنجلاديشي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "باربادوسي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بربودا";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بوتسواني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بيلاروسي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بلجيكي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بليزي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بنيني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بوتاني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بوليفي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بوسني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "برازيلي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بريطاني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بروناى";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بلغاري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بوركيني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بورمي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بوروندي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "كمبودي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "كاميروني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "كندي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "االرأس الأخضر";
        $nation->save();
        $nation = new Nation();
        $nation->name = "وسط أفريقيا";
        $nation->save();
        $nation = new Nation();
        $nation->name = "تشادي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "شيلي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "صينى";
        $nation->save();
        $nation = new Nation();
        $nation->name = "كولومبي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "جزر القمر";
        $nation->save();
        $nation = new Nation();
        $nation->name = "كونغولي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "كوستاريكي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "كرواتية";
        $nation->save();
        $nation = new Nation();
        $nation->name = "كوبي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "قبرصي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "تشيكي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "دانماركي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "جيبوتي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "دومينيكاني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "هولندي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "تيموري شرقي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "اكوادوري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "مصري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "إماراتي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "غيني  استوائي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "إريتري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "إستوني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "حبشي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "فيجي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "فلبيني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "فنلندي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "فرنسي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "جابوني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "غامبيي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "جورجي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ألماني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "غاني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "إغريقي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "جرينادي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "غواتيمالي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "غيني بيساوي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "غيني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "جوياني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "هايتي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "هرسكي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "هندوراسي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "هنغاري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "إيسلندي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "هندي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "إندونيسي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "إيراني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "عراقي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "إيرلندي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "إيطالي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "إفواري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "جامايكي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ياباني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "أردني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "كازاخستاني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "كيني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "كيتياني ونيفيسياني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "كويتي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "قيرغيزستان";
        $nation->save();
        $nation = new Nation();
        $nation->name = "لاوسي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "لاتفي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "لبناني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ليبيري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ليبي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ليختنشتايني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "لتواني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "لكسمبرغي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "مقدوني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "مدغشقري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "مالاوى";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ماليزي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "مالديفي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "مالي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "مالطي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "مارشالي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "موريتاني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "موريشيوسي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "مكسيكي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ميكرونيزي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "مولدوفي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "موناكو";
        $nation->save();
        $nation = new Nation();
        $nation->name = "منغولي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "مغربي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ليسوتو";
        $nation->save();
        $nation = new Nation();
        $nation->name = "لتسواني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "موزمبيقي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ناميبي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ناورو";
        $nation->save();
        $nation = new Nation();
        $nation->name = "نيبالي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "نيوزيلندي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ني فانواتي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "نيكاراغوا";
        $nation->save();
        $nation = new Nation();
        $nation->name = "نيجري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "كوري شمالي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "إيرلندي شمالي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "نرويجي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "عماني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "باكستاني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بالاوي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "فلسطيني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بنمي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بابوا غينيا الجديدة";
        $nation->save();
        $nation = new Nation();
        $nation->name = "باراغواياني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بيروفي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "بولندي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "برتغالي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "قطري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "روماني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "روسي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "رواندي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "لوسياني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سلفادوري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ساموايان";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سان مارينيز";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ساو توميان";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سعودي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سكتلندي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سنغالي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "صربي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سيشلي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سيرا ليوني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سنغافوري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سلوفاكي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سلوفيني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "جزر سليمان";
        $nation->save();
        $nation = new Nation();
        $nation->name = "صومالي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "جنوب افريقيي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "كوري جنوبي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "إسباني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سري لانكي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سوداني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سورينامي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سوازي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سويدي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سويسري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "سوري";
        $nation->save();
        $nation = new Nation();
        $nation->name = "تايواني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "طاجيكي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "تنزاني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "التايلاندي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "توغواني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "تونجاني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ترينيدادي أو توباغوني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "تونسي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "تركي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "توفالي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "أوغندي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "أوكراني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "أوروجواي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "أوزبكستاني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "فنزويلي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "فيتنامي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "ويلزي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "يمني";
        $nation->save();
        $nation = new Nation();
        $nation->name = "زامبي";
        $nation->save();
        $nation = new Nation();
        $nation->name = "زيمبابوي";
    }
}
